DancinGoat/DancingGoatMvc/Models/References/ReferenceViewModel.cs
using CMS.DocumentEngine.Types.DancingGoatMvc;

using Kentico.Content.Web.Mvc;

namespace DancingGoat.Models.References
{
    public class ReferenceViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public string Text { get; set; }

        public string ImagePath { get; set; }


        public static ReferenceViewModel GetViewModel(Reference reference, IPageAttachmentUrlRetriever attachmentUrlRetriever)
        {
            if (reference == null)
            {
                return null;
            }

            return new ReferenceViewModel
            {
                Name = reference.ReferenceName,
                Description = reference.ReferenceDescription,
                Text = reference.ReferenceText,
                ImagePath = attachmentUrlRetriever.Retrieve(reference.Fields.Image).RelativePath
            };
        }
    }
}

DancinGoat/DancingGoatMvc/Controllers/CompanyController.cs
using System.Linq;
using System.Web.Mvc;

using DancingGoat.Models.Contacts;
using DancingGoat.Models.SocialLinks;
using DancingGoat.Repositories;

using Kentico.Content.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IContactRepository contactRepository;
        private readonly ICountryRepository countryRepository;
        private readonly ISocialLinkRepository socialLinkRepository;
        private readonly IPageAttachmentUrlRetriever attachmentUrlRetriever;


        public CompanyController(ISocialLinkRepository socialLinkRepository,
            IContactRepository contactRepository,
            ICountryRepository countryRepository, 
            IPageAttachmentUrlRetriever attachmentUrlRetriever)
        {
            this.countryRepository = countryRepository;
            this.socialLinkRepository = socialLinkRepository;
            this.contactRepository = contactRepository;
            this.attachmentUrlRetriever = attachmentUrlRetriever;
        }


        [ChildActionOnly]
        [ValidateInput(false)]
        public ActionResult CompanyAddress()
        {
            var address = GetCompanyContactModel();

            return PartialView("_Address", address);
        }

        [ChildActionOnly]
        [ValidateInput(false)]
        public ActionResult CompanyInfo()
        {
            var info = GetCompanyContactModel();

            return PartialView("_Info", info);
        }

        [ChildActionOnly]
        [ValidateInput(false)]
        public ActionResult CompanySocialLinks()
        {
            var socialLinks = socialLinkRepository.GetSocialLinks();

            return PartialView("_SocialLinks", socialLinks.Select(link => SocialLinkViewModel.GetViewModel(link, attachmentUrlRetriever)));
        }


        private ContactViewModel GetCompanyContactModel()
        {
            return ContactViewModel.GetViewModel(contactRepository.GetCompanyContact(), countryRepository);
        }
    }
}

DancinGoat/DancingGoatMvc/Controllers/ConsentController.cs
using System.Net;
using System.Threading;
using System.Web.Mvc;

using CMS.ContactManagement;
using CMS.DataProtection;
using CMS.Helpers;

using DancingGoat.Helpers.Generator;
using DancingGoat.Models.Consent;

namespace DancingGoat.Controllers
{
    public class ConsentController : Controller
    {
        private readonly ICurrentCookieLevelProvider cookieLevelProvider;
        private readonly IConsentAgreementService consentAgreementService;
        private readonly IConsentInfoProvider consentInfoProvider;


        public ConsentController(ICurrentCookieLevelProvider cookieLevelProvider, IConsentAgreementService consentAgreementService, IConsentInfoProvider consentInfoProvider)
        {
            this.cookieLevelProvider = cookieLevelProvider;
            this.consentAgreementService = consentAgreementService;
            this.consentInfoProvider = consentInfoProvider;
        }


        // GET: Consent
        public ActionResult Index()
        {
            return new EmptyResult();
        }


        // POST: Consent/Agree
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agree()
        {
            var resultStatus = HttpStatusCode.BadRequest;

            var consent = consentInfoProvider.Get(TrackingConsentGenerator.CONSENT_NAME);
            if (consent != null)
            {
                cookieLevelProvider.SetCurrentCookieLevel(CookieLevel.All);
                
                var contact = ContactManagementContext.CurrentContact;
                if (contact != null) 
                { 
                    consentAgreementService.Agree(contact, consent);
                }

                resultStatus = HttpStatusCode.OK;
            }

            // Redirect is handled on client by javascript
            return new HttpStatusCodeResult(resultStatus);
        }
    }
}

DancinGoat/DancingGoatMvc/Views/Shared/_GoogleMaps.cshtml
@using CMS.Base

<script src="https://maps.googleapis.com/maps/api/js?key=@SettingsHelper.AppSettings["GoogleMapsApiKey"]"></script>
@Scripts.Render("~/Scripts/map.js")

DancinGoat/DancingGoatMvc/Views/Shared/_Layout.cshtml
@using Kentico.Membership.Web.Mvc
@using Kentico.Content.Web.Mvc
@using DancingGoat.Models.Widgets

<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    @Html.Kentico().PageTitle(ViewBag.Title as string)
    <link rel="icon" href="~/content/images/favicon.png" type="image/png" />
    <link href="~/Content/Styles/Site.css" rel="stylesheet" type="text/css" />
    
    <link href="~/Content/css/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/media-sm.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Styles/bootstrap-4.0.0.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Styles/SiteOptivo.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="@Url.Kentico().PageCanonicalUrl()" />
    @RenderSection("styles", required: false)
    @Html.Kentico().ABTestLoggerScript()
    @Html.Kentico().ActivityLoggingScript()
    @Html.Kentico().WebAnalyticsLoggingScript()
</head>
<body>
    <div class="page-wrap">
        @Html.Action("Index", "Consent")
        <!--OptivoMenu-->
        <div class="mobile-nav topnav">
            <a href="/home" class="logo active">
                <img id="logo" src="~/Content/Images/Header.svg">
            </a>
            <!-- Navigation links (hidden by default) -->
            <div id="myLinks">
                @Html.Action("Menu", "Navigation")
            </div>
            <!-- "Hamburger menu" / "Bar icon" to toggle the navigation links -->
            <a href="javascript:void(0);" class="icon" onclick="navbarMobile()">
                <i class="fa fa-bars mt-2"></i>
            </a>
        </div>
        <!--end of mobile navbar-->
        <div class="desktop-nav header">
            <a href="/home" class="logo active">
                <img id="logo" src="~/Content/Images/Header.svg">
            </a>
            <nav role="navigation">
                <ul id="navlist" class="mt-2 d-flex">
                    @Html.Action("Menu", "Navigation")

                </ul>
            </nav>
        </div>
        <script>
            var path = window.location.pathname;
            var dir = path.substring(path.indexOf('/') + 1, path.length);
            if (dir == "blogs" || dir == "testimonial") {
                var x = document.getElementById("Desktop-Nav");
                x.classList.add("nav-black")
            }
        </script>
        <div>
            @RenderBody()
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <div id="cookiebarBox" class="os-animation" data-os-animation="fadeIn">
        <div class="container-cookie risk-dismiss" style="display: block;">
            <p>Like most websites, this site uses cookies to assist with navigation and your ability to provide feedback, analyse your use of products and services so that we can improve them, assist with our personal promotional and marketing efforts and provide consent from third parties.</p>
            <a id="cookieBoxok" class="cookieok" data-cookie="risk">OK</a>
        </div>
    </div>
    <script>
        // if you want to see a cookie, delete 'seen-cookiePopup' from cookies first.

jQuery(document).ready(function($) {
   // Get CookieBox
  var cookieBox = document.getElementById('cookiebarBox');
	// Get the <span> element that closes the cookiebox
  var closeCookieBox = document.getElementById("cookieBoxok");
    closeCookieBox.onclick = function() {
        cookieBox.style.display = "none";
    };
});

(function () {
    function createCookie(name, value, days, path) {
        var expires = "";
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toGMTString();
        }
        else expires = "";
        document.cookie = name + "=" + value + expires + "; path=" + path;
    }

    function readCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') c = c.substring(1, c.length);
            if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
        }
        return null;
    }

    // Set/update cookie
    var cookieExpiry = 30;
    var cookiePath = "/";

    document.getElementById("cookieBoxok").addEventListener('click', function () {
        createCookie('seen-cookiePopup', 'yes', cookieExpiry, cookiePath);
    });

    var cookiePopup = readCookie('seen-cookiePopup');
    if (cookiePopup != null && cookiePopup == 'yes') {
        cookiebarBox.style.display = 'none';
    } else {
        cookiebarBox.style.display = 'block';
    }
})();
    </script>

    <div class="footer">
        <div class="row">
            <div class="col-lg-3 col-sm-12 footer-item contact-footer">
                <div class="row">
                    <img id="logo" class="footer-logo-mobile"
                         src="./images/Header.svg">
                </div>
                <div class="row">
                    <div class="golden-text mb-2">@ResHelper.GetString("DancingGoatMvc.Contact.Title")</div>
                </div>
                @Html.Action("CompanyAddress", "Company")
            </div>
            @Html.Action("Footer", "Navigation")
            <div class="col-lg-3 col-sm-12 footer-item general-footer-info">
                <div class="row d-flex mb-5">
                    @Html.Action("CompanySocialLinks", "Company")
                </div>
                @Html.Action("CompanyInfo", "Company")
                <div class="row">
                    <div class="info-text">&copy; @DateTime.Now.Year Optivo. All rights reserved.</div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-unobtrusive-ajax")
    @Scripts.Render("~/bundles/jquery-validation")
    @Scripts.Render("~/Scripts/responsiveMenuDropdown.js")
    @Scripts.Render("~/Scripts/bootstrap-4.0.0.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.min.js")
    @Scripts.Render("~/Scripts/optivo.js")
    @Scripts.Render("~/Scripts/mobileMenu.js")
    @Scripts.Render("~/Scripts/gallery.js")
    @Scripts.Render("~/Scripts/popper-4.0.0.min.js")
    @Scripts.Render("~/Scripts/calendar.js")



    @RenderSection("scripts", required: false)

</body>
</html>

DancinGoat/DancingGoatMvc/Views/Shared/_ManufacturerList.cshtml
@using DancingGoat.Models.Manufacturers;
@model IEnumerable<ManufactureListItemViewModel>

    <div class="row manufacturer-list">
        @if (Model != null && Model.Any())
        {
            foreach (var manufacturer in Model)
            {
                <div class="col-md-4 col-lg-3 manufacturer-item">
                    <a href="@manufacturer.Url">
                        <img src="@manufacturer.ImagePath" />
                    </a>
                </div>
            }
        }
        else
        {
            <span class="ContentLabel">@ResHelper.GetString("DancingGoatMvc.Manufacturers.NoMatchingManufacturers")</span>
        }
    </div>

DancinGoat/DancingGoatMvc/Views/Shared/_Reference.cshtml
@model DancingGoat.Models.References.ReferenceViewModel

<section class="row reference">
    <h1 class="title-tab">@ResHelper.GetString("DancingGoatMvc.AboutUs.Reference")</h1>
    <div class="col-sm-12 full-height">
        <div class="col-md-5 col-lg-3 sm-hidden">
            <img src="@Model.ImagePath" alt="@Model.Name" title="@Model.Name" class="image-responsive" />
        </div>
        <div class="col-sm-12 col-md-7 col-lg-9 quote">
            <div class="text"><span>&ldquo;</span>@Html.Raw(Model.Text)<span>&rdquo;</span></div>
            <div class="name-and-description">
                <div class="name">@Html.Raw(Model.Name)</div>
                <div class="description">@Html.Raw(Model.Description)</div>
            </div>
        </div>
    </div>
</section>

DancinGoat/DancingGoatMvc/Views/Shared/_StoreLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container product-page-container">
    <nav role="navigation" class="sub-menu row">
        <div class="store-menu-list row">
            <ul>
                <li>
                    @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.COFFEES), ResHelper.GetString("DancingGoatMvc.Coffees"))
                </li>
                <li>
                    @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.BREWERS), ResHelper.GetString("DancingGoatMvc.Brewers"))
                </li>
                <li>
                    @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.ACCESSORIES), ResHelper.GetString("DancingGoatMvc.Accessories"))
                </li>
                <li>
                    @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.GRINDERS), ResHelper.GetString("DancingGoatMvc.Grinders"))
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
</div>

@section Scripts {
    @RenderSection("scripts", required: false)
}

DancinGoat/DancingGoatMvc/Views/Shared/_StoreProductList.cshtml
@using DancingGoat.Models.Products
@model IEnumerable<ProductListItemViewModel>
    
@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 4 products on row for large screen -->
        <div class="col-md-4 col-lg-3">
            @Html.DisplayFor(m => product, "ProductListItem")
        </div>
    }
}
else
{
    <span class="ContentLabel">@ResHelper.GetString("DancingGoatMvc.Store.NoMatchingProducts")</span>
}

DancinGoat/DancingGoatMvc/Views/Shared/_TrackingConsent.cshtml
@model DancingGoat.Models.Consent.ConsentViewModel

<div id="consent" class="cookie-consent">
    @if (!Model.IsConsentAgreed)
    {
        <div class="consent-text">@Model.ConsentNotAgreedText</div>
        <div>@Model.ConsentShortText</div>
        using (Ajax.BeginForm("Agree", "Consent", new AjaxOptions { HttpMethod = "Post", OnComplete = "new function(){window.location.reload()}" }, new { @class = "consent-buttons" }))
        {
            @Html.Kentico().AntiForgeryToken()
            <input type="submit" value="@Model.AgreeButtonText" class="btn btn-default btn-consent">
        }
    }
    else
    {
        <div>
            @Model.ConsentAgreedText @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.PRIVACY), Model.PrivacyPageLinkText).
        </div>
    }
</div>