DancinGoat/DancingGoatMvc/Models/Checkout/AddressSelectorViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace DancingGoat.Models.Checkout
{
    public class AddressSelectorViewModel
    {
        [Display(Name = "DancingGoatMvc.Address")]
        public int? AddressID { get; set; }
        

        public SelectList Addresses { get; set; }


        public bool HasSomeAddress => (Addresses != null) && Addresses.Any();
    }
}

DancinGoat/DancingGoatMvc/Models/Checkout/BillingAddressViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

using CMS.Ecommerce;
using CMS.Globalization;

using DancingGoat.Repositories;

namespace DancingGoat.Models.Checkout
{
    [Bind(Exclude = "Countries")]
    public class BillingAddressViewModel
    {
        [Required]
        [Display(Name = "DancingGoatMvc.Address.Line1")]
        [MaxLength(100, ErrorMessage = "DancingGoatMvc.General.MaximumInputLengthExceeded")]
        public string BillingAddressLine1 { get; set; }



        [Display(Name = "DancingGoatMvc.Address.Line2")]
        [MaxLength(100, ErrorMessage = "DancingGoatMvc.General.MaximumInputLengthExceeded")]
        public string BillingAddressLine2 { get; set; }


        [Required]
        [Display(Name = "DancingGoatMvc.Address.City")]
        [MaxLength(100, ErrorMessage = "DancingGoatMvc.General.MaximumInputLengthExceeded")]
        public string BillingAddressCity { get; set; }


        [Required]
        [Display(Name = "DancingGoatMvc.Address.Zip")]
        [MaxLength(20, ErrorMessage = "DancingGoatMvc.General.MaximumInputLengthExceeded")]
        public string BillingAddressPostalCode { get; set; }
        

        public CountryStateViewModel BillingAddressCountryStateSelector { get; set; }


        public AddressSelectorViewModel BillingAddressSelector { get; set; }


        public SelectList Countries { get; set; }


        public string BillingAddressState { get; set; }


        public string BillingAddressCountry { get; set; }


        public BillingAddressViewModel()
        {
        }


        public BillingAddressViewModel(AddressInfo address, SelectList countries, ICountryRepository countryRepository, SelectList addresses = null)
        {
            if (address != null)
            {
                if (countryRepository == null)
                {
                    throw new ArgumentNullException(nameof(countryRepository));
                }

                BillingAddressLine1 = address.AddressLine1;
                BillingAddressLine2 = address.AddressLine2;
                BillingAddressCity = address.AddressCity;
                BillingAddressPostalCode = address.AddressZip;
                BillingAddressState = countryRepository.GetState(address.AddressStateID)?.StateDisplayName ?? String.Empty;
                BillingAddressCountry = countryRepository.GetCountry(address.AddressCountryID)?.CountryDisplayName ?? String.Empty;
                Countries = countries;
            }

            BillingAddressCountryStateSelector = new CountryStateViewModel
            {
                Countries = countries,
                CountryID = address?.AddressCountryID ?? 0,
                StateID = address?.AddressStateID ?? 0
            };

            BillingAddressSelector = new AddressSelectorViewModel
            {
                Addresses = addresses,
                AddressID = address?.AddressID ?? 0
            };
        }


        public void ApplyTo(AddressInfo address)
        {
            address.AddressLine1 = BillingAddressLine1;
            address.AddressLine2 = BillingAddressLine2;
            address.AddressCity = BillingAddressCity;
            address.AddressZip = BillingAddressPostalCode;
            address.AddressCountryID = BillingAddressCountryStateSelector.CountryID;
            address.AddressStateID = BillingAddressCountryStateSelector.StateID ?? 0;
        }
    }
}

DancinGoat/DancingGoatMvc/Models/Checkout/CartItemUpdateModel.cs
using System.ComponentModel.DataAnnotations;

namespace DancingGoat.Models.Checkout
{
    public class CartItemUpdateModel
    {
        public int ID { get; set; }


        public int SKUID { get; set; }


        [Range(0, int.MaxValue, ErrorMessage = "DancingGoatMvc.ShoppingCart.UnitsGreaterThanZero")]
        public int Units { get; set; }
    }
}

DancinGoat/DancingGoatMvc/Models/Checkout/CartItemViewModel.cs
namespace DancingGoat.Models.Checkout
{
    public class CartItemViewModel
    {
        public int SKUID { get; set; }

        public string SKUImagePath { get; set; }

        public string SKUName { get; set; }

        public int CartItemID { get; set; }

        public int CartItemUnits { get; set; }

        public decimal TotalPrice { get; set; }
    }
}

DancinGoat/DancingGoatMvc/Models/Checkout/CountryStateViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DancingGoat.Models.Checkout
{
    [Bind(Exclude = "Countries")]
    public class CountryStateViewModel
    {
        [Required(ErrorMessage = "DancingGoatMvc.Address.CountryIsRequired")]
        [Display(Name = "DancingGoatMvc.Address.Country")]
        public int CountryID { get; set; }


        [Display(Name = "DancingGoatMvc.Address.State")]
        [RegularExpression(@"[0-9]*$", ErrorMessage = "DancingGoatMvc.Address.StateIsRequired")]
        public int? StateID { get; set; }


        public SelectList Countries { get; set; }
    }
}

DancinGoat/DancingGoatMvc/Models/Checkout/CouponCodesUpdateModel.cs
using System.ComponentModel.DataAnnotations;

namespace DancingGoat.Models.Checkout
{
    public class CouponCodesUpdateModel
    {
        [MaxLength(200, ErrorMessage = "DancingGoatMvc.General.MaximumInputLengthExceeded")]
        public string NewCouponCode { get; set; }


        public string RemoveCouponCode { get; set; }
    }
}

DancinGoat/DancingGoatMvc/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Globalization;
using CMS.Helpers;

using Kentico.Content.Web.Mvc;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Repositories;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly ICheckoutService checkoutService;
        private readonly IContactRepository contactRepository;
        private readonly IProductRepository productRepository;
        private readonly IPageUrlRetriever pageUrlRetriever;
        private readonly ISKUInfoProvider skuInfoProvider;
        private readonly ICountryInfoProvider countryInfoProvider;
        private readonly IStateInfoProvider stateInfoProvider;


        public CheckoutController(IShoppingService shoppingService, IContactRepository contactRepository, IProductRepository productRepository, 
            ICheckoutService checkoutService, IPageUrlRetriever pageUrlRetriever, ISKUInfoProvider skuInfoProvider, ICountryInfoProvider countryInfoProvider,
            IStateInfoProvider stateInfoProvider)
        {
            this.shoppingService = shoppingService;
            this.contactRepository = contactRepository;
            this.checkoutService = checkoutService;
            this.productRepository = productRepository;
            this.pageUrlRetriever = pageUrlRetriever;
            this.skuInfoProvider = skuInfoProvider;
            this.countryInfoProvider = countryInfoProvider;
            this.stateInfoProvider = stateInfoProvider;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    shoppingService.SetCustomer(customer);
                }

                shoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = checkoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (shoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model)
        {
            var cart = shoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", ResHelper.GetString("DancingGoatMvc.Checkout.EmptyCartError"));

                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!checkoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", ResHelper.GetString("DancingGoatMvc.Payment.PaymentMethodRequired"));
            }
            else
            {
                shoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart, skuInfoProvider, countryInfoProvider, stateInfoProvider);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                shoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model)
        {
            // Check the selected shipping option
            bool isShippingNeeded = shoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !checkoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", ResHelper.GetString("DancingGoatMvc.Shipping.ShippingOptionRequired"));
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!checkoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", ResHelper.GetString("DancingGoatMvc.Address.CountryIsRequired"));
            }
            else if (!checkoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", ResHelper.GetString("DancingGoatMvc.Address.StateIsRequired"));
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            shoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = checkoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            shoppingService.SetBillingAddress(billingAddress);
            shoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = contactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult UpdateItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.UpdateItemQuantity(item.ID, item.Units);
            }
            else
            {
                // Add an item error and save ViewData so that the ShoppingCart action can show validation errors
                var key = item.ID.ToString();
                ModelState.Add(key, ModelState["Units"]);
            }

            var cartViewModel = checkoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveItem(CartItemUpdateModel item)
        {
            shoppingService.RemoveItemFromCart(item.ID);

            var cartViewModel = checkoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {

DancinGoat/DancingGoatMvc/Controllers/CouponController.cs
using System.Web.Mvc;

using CMS.Ecommerce;
using CMS.Helpers;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Services;

namespace DancingGoat.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly ICheckoutService checkoutService;


        public CouponController(IShoppingService shoppingService, ICheckoutService checkoutService)
        {
            this.shoppingService = shoppingService;
            this.checkoutService = checkoutService;
        }


        // GET: Coupon/Show
        public ActionResult Show()
        {
            var viewModel = checkoutService.PrepareCartViewModel();

            return PartialView("_CouponCodeEdit", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddCouponCode(CouponCodesUpdateModel model)
        {
            string couponCode = model.NewCouponCode?.Trim();
            if (string.IsNullOrEmpty(couponCode) || !shoppingService.AddCouponCode(couponCode))
            {
                return new JsonResult
                {
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    Data = new { CouponCodeInvalidMessage = ResHelper.GetString("DancingGoatMvc.Checkout.CouponCodeInvalid") }
                };

            }

            return new EmptyResult();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveCouponCode(CouponCodesUpdateModel model)
        {
            shoppingService.RemoveCouponCode(model.RemoveCouponCode);

            return new EmptyResult();
        }
    }
}

DancinGoat/DancingGoatMvc/Views/Checkout/DeliveryDetails.cshtml
@model DancingGoat.Models.Checkout.DeliveryDetailsViewModel

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.CustomerDetails");
}

<div class="checkout-container">
    <div class="container cart">
        <div class="checkout-back-link">
            <a href="@Url.Action("ShoppingCart")">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.BackToShoppingCart")</a>
        </div>

        @using (Html.BeginForm("DeliveryDetails", "Checkout", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-4">
                    <div class="customer-details">
                        <div class="form-horizontal">
                            @Html.EditorFor(m => m.Customer)
                            @Html.EditorFor(m => m.BillingAddress)
                            @if (Model.ShippingOption.IsVisible)
                            {
                                @Html.EditorFor(m => m.ShippingOption)
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-md-offset-4">

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <h2>@ResHelper.GetString("DancingGoatMvc.DeliveryDetails.AlreadyCustomer")</h2>
                        <p>@ResHelper.GetString("DancingGoatMvc.DeliveryDetails.AccessDetails")</p>
                        @Html.ActionLink(ResHelper.GetString("DancingGoatMvc.DeliveryDetails.SignIn"), "Login", "Account", new { returnUrl = Server.UrlEncode(Request.RawUrl) }, new { @class = "btn btn-secondary btn-default" })
                    }

                    <div class="gray-box floating-box">
                        <p>@ResHelper.GetString("DancingGoatMvc.Checkout.FillDetailsAndProceed")</p>
                        <input type="submit" class="btn btn-primary btn-default checkout-button" value="@ResHelper.GetString("DancingGoatMvc.Checkout.ReviewOrder")" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/countryStateSelector.js")
    @Scripts.Render("~/Scripts/addressSelector.js")
}

DancinGoat/DancingGoatMvc/Views/Checkout/PreviewAndPay.cshtml
@model DancingGoat.Models.Checkout.PreviewViewModel

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.ShoppingCartPreview");
}

<div class="checkout-container">
    <div class="cart">
        <div class="continue-shopping-link">
            <a href="@Url.Action("DeliveryDetails")">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.BackToCustomerDetails")</a>
        </div>

        @Html.ValidationSummary(true, ResHelper.GetString("DancingGoatMvc.Checkout.OrderFailed"), new { @class = "ErrorLabel red" })
        <div>
            @Html.ValidationMessage("shipping", new { @class = "red" })
        </div>
        <div>
            @Html.ValidationMessage("cart.empty", new { @class = "red" })
        </div>

        <div class="col-md-8 cart-content">
            <div class="row">
                <div class="col-md-6">
                    <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.BillingDetails")</h2>

                    @Html.DisplayFor(m => m.CustomerDetails)

                    <br />

                    @Html.DisplayFor(m => m.BillingAddress)
                </div>
                @if (Model.DeliveryDetails.ShippingOption.IsVisible)
                {
                    <div class="col-md-6">
                        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.ShippingDetails")</h2>
                        <span>@Model.ShippingName</span>
                        <br />
                        <div>@Model.CustomerDetails.Company</div>

                        <br />

                        @Html.DisplayFor(m => m.BillingAddress)
                    </div>
                }
            </div>
            <div class="row">
                <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.OrderedItems")</h2>
                <hr class="first-separator" />

                @Html.Partial("_ShoppingCartContentPreview", Model.CartModel)
            </div>
        </div>
        <div class="col-md-4">
            <div class="cart-right-panel floating-box">
                <div id="shoppingCartTotals">
                    @Html.Partial("_ShoppingCartTotals", Model.CartModel)
                </div>

                @using (Html.BeginForm("PreviewAndPay", "Checkout", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.EditorFor(m => m.PaymentMethod)
                    <input type="submit" value="@ResHelper.GetString("DancingGoatMvc.Checkout.ConfirmAndPayButton")" class="btn-primary checkout-button btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

DancinGoat/DancingGoatMvc/Views/Checkout/ShoppingCart.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@section Scripts{
    <script type="text/javascript">$('#couponCode').load('@HttpUtility.JavaScriptStringEncode(Url.Action("Show", "Coupon"))')</script>
}

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.ShoppingCart");
}

<div class="checkout-container">
    <div class="cart">
        <div class="continue-shopping-link">
            <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.COFFEES)">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.ContinueShopping")</a>
        </div>

        @if (!ViewData.ModelState.IsValid)
        {
            @Html.ValidationSummary(null, new { @class = "invalid-cart-content" })
        }

        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.YourShoppingCart")</h2>
        <div class="col-md-8 cart-content">
            <hr class="first-separator" />
            @if (Model.IsEmpty)
            {
                <span>@ResHelper.GetString("DancingGoatMvc.Checkout.ShoppingCartIsEmpty")</span>
                <hr class="last-separator" />
            }
            else
            {
                @Html.Partial("_ShoppingCartContentEdit", Model)
            }

            @if (Model.RemainingAmountForFreeShipping > 0)
            {
                <section class="free-shipping-promotion">
                    <div>
                        <span>
                            @ResHelper.GetStringFormat("DancingGoatMvc.ShoppingCart.FreeDelivery", Model.FormatPrice(Model.RemainingAmountForFreeShipping))
                        </span>
                    </div>
                </section>
            }
        </div>
        <div class="col-md-4">
            <div class="cart-right-panel floating-box">
                <div id="couponCode"></div>
                <hr>

                @using (Html.BeginForm("ShoppingCart", "Checkout", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.Partial("_ShoppingCartTotals", Model)

                    <p>@ResHelper.GetString("DancingGoatMvc.Checkout.ReviewAndCheckout")</p>

                    <input type="submit" name="ShoppingCartCheckout" value="@ResHelper.GetString("DancingGoatMvc.Checkout")" class="btn-primary checkout-button btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

DancinGoat/DancingGoatMvc/Views/Checkout/ThankYou.cshtml
@model DancingGoat.Models.Checkout.ThankYouViewModel

@{ 
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.ThankYou");
}

<div class="col-md-6 col-lg-5">
    <div class="thank-you-content">
        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.ThankYou")</h2>

        <p>@ResHelper.GetString("DancingGoatMvc.Order.Success")</p>
        <p>@Html.Raw(ResHelper.GetStringFormat("DancingGoatMvc.Order.Questions", Model.Phone))</p>
    </div>
</div>

DancinGoat/DancingGoatMvc/Views/Checkout/_ShoppingCartContentEdit.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@foreach (var cartItem in Model.CartItems)
{
    <div class="row">
        <div class="col-md-10">
            @if (!string.IsNullOrEmpty(cartItem.SKUImagePath))
            {
                <div class="cart-item-image">
                    <a href="@Url.Action("ItemDetail", new { skuId = cartItem.SKUID })">
                        <img src="@cartItem.SKUImagePath" alt="@cartItem.SKUName" title="@cartItem.SKUName" />
                    </a>
                </div>
            }
            <div class="cart-item-info">
                @Html.ActionLink(cartItem.SKUName, "ItemDetail", new { skuId = cartItem.SKUID })
            </div>
            @using (Html.BeginForm("ShoppingCart", "Checkout", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="cart-item-amount">
                    <span>Qty</span>
                    <input type="hidden" name="ID" value="@cartItem.CartItemID" />
                    <input type="text" name="Units" value="@cartItem.CartItemUnits" class="form-control" />
                    <input type="submit" name="UpdateItem" value="@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Update")" class="btn btn-default" />
                    <input type="submit" name="RemoveItem" value="@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Remove")" class="btn btn-default" />
                </div>
            }
            @Html.ValidationMessage(cartItem.CartItemID.ToString(), new { @class = "red"})
        </div>
        <div class="col-md-2 cart-item-subtotal">
            <span>@Model.FormatPrice(cartItem.TotalPrice)</span>
        </div>
    </div>
    <hr />
}

DancinGoat/DancingGoatMvc/Views/Checkout/_ShoppingCartContentPreview.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@foreach (var cartItem in Model.CartItems)
{
    <div class="row">
        <div class="col-md-10">
            @if (!string.IsNullOrEmpty(cartItem.SKUImagePath))
            {
                <div class="cart-item-image">
                    <a href="@Url.Action("ItemDetail", new { skuId = cartItem.SKUID })">
                        <img src="@cartItem.SKUImagePath" alt="@cartItem.SKUName" title="@cartItem.SKUName" />
                    </a>
                </div>
            }
            <div class="cart-item-info">
                @Html.ActionLink(cartItem.SKUName, "ItemDetail", new { skuId = cartItem.SKUID })
            </div>
            <div class="cart-item-amount">
                <span>Qty</span>
                <input type="text" name="Units" value="@cartItem.CartItemUnits" class="form-control" disabled />
            </div>

            @Html.ValidationMessage(cartItem.CartItemID.ToString(), new { @class = "red" })

        </div>
        <div class="col-md-2 cart-item-subtotal">
            <span>@Model.FormatPrice(cartItem.TotalPrice)</span>
        </div>
    </div>
    <hr />
}

DancinGoat/DancingGoatMvc/Views/Checkout/_ShoppingCartTotals.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@{
    var tax = Model.TotalTax;
    var shipping = Model.TotalShipping;
}

@if (tax > 0)
{
    <div class="cart-total-viewer">
        <div class="label">
            @ResHelper.GetString("DancingGoatMvc.ShoppingCart.TotalTax")
        </div>
        <div class="value">
            @Model.FormatPrice(tax)
        </div>
    </div>
}

@if (shipping > 0)
{
    <div class="cart-total-viewer">
        <div class="label">
            @ResHelper.GetString("DancingGoatMvc.ShoppingCart.Shipping")
        </div>
        <div class="value">
            @Model.FormatPrice(shipping)
        </div>
    </div>
}


@if ((tax > 0) || (shipping > 0))
{
    <hr />
}

<div class="cart-total">
    <div class="cart-total-viewer">
        <div class="label">
            <span>@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Total")</span>
        </div>
        <div class="value">
            <span>@Model.FormatPrice(Model.GrandTotal)</span>
        </div>
    </div>
</div>